# Generated by Django 4.2.13 on 2024-05-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
