# Generated by Django 4.2.13 on 2024-05-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasal_app', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
